config/routes.rb
Rails.application.routes.draw do
    get 'notes/:id/users', to: 'notes#newsharing' ,as: 'new_sharing_note'
  post 'notes/:id/users', to: 'notes#createsharing' ,as: 'create_sharing_note'
  get 'notecollections/:id/users', to: 'notecollections#newsharing' ,as: 'new_sharing_notecollection'
  post 'notecollections/:id/users', to: 'notecollections#createsharing' ,as: 'create_sharing_notecollection'
  resources :notecollections
  resources :notes
  root to: "notes#index"
  devise_for :users
    as :user do
        get '/users', to: 'users/sessions#index'
        #post '/users', to: 'users/registrations#create'
        #get '/users/new', to: 'users/registrations#new' , as: "new_user"
        get '/users/:id', to: 'users/sessions#show' , as: "user"
        get '/users/:id/edit', to: 'users/sessions#edit' , as: "edit_user"
        patch '/users/:id', to: 'users/sessions#update'
        post '/users/:id/acc', to: 'users/sessions#acceptfriend' ,as: 'acc_friend'
        post '/users/:id/add', to: 'users/sessions#addfriend' ,as: 'add_friend'
        post '/users/:id/rev', to: 'users/sessions#revokefriend' ,as: 'rev_friend'
        delete '/users/:id', to: 'users/sessions#destroy'
end

    get '/friendships', to: 'friendships#index'
    delete 'friendships/:id/destroy_friendship', to: 'friendships#destroy', as: 'destroy_friendship'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/notecollection.rb
class Notecollection < ApplicationRecord
  has_and_belongs_to_many :notes
  has_and_belongs_to_many :users
end

app/controllers/notecollections_controller.rb
class NotecollectionsController < ApplicationController
  before_action :set_notecollection, only: [:show, :edit, :update, :destroy,:newsharing,:createsharing]
before_action :authenticate_user!
  # GET /notecollections
  # GET /notecollections.json
  def index
    if current_user.admin?
        @notecollections = Notecollection.all
    else
    @notecollections = current_user.notecollections
    end
  end

  # GET /notecollections/1
  # GET /notecollections/1.json
  def show
  end

  # GET /notecollections/new
  def new
    @notecollection = Notecollection.new
    @note = current_user.notes
  end

  # GET /notecollections/1/edit
  def edit
    @note = current_user.notes
  end

  # POST /notecollections
  # POST /notecollections.json
  def create
    @notecollection = Notecollection.new(notecollection_params)
    @notecollection.users << current_user
    respond_to do |format|
      if @notecollection.save
        format.html { redirect_to @notecollection, notice: 'Notecollection was successfully created.' }
        format.json { render :show, status: :created, location: @notecollection }
      else
        format.html { render :new }
        format.json { render json: @notecollection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notecollections/1
  # PATCH/PUT /notecollections/1.json
  def update
    respond_to do |format|
      if @notecollection.update(notecollection_params)
        format.html { redirect_to @notecollection, notice: 'Notecollection was successfully updated.' }
        format.json { render :show, status: :ok, location: @notecollection }
      else
        format.html { render :edit }
        format.json { render json: @notecollection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notecollections/1
  # DELETE /notecollections/1.json
  def destroy
    @notecollection.destroy
    respond_to do |format|
      format.html { redirect_to notecollections_url, notice: 'Notecollection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

def newsharing
     @user =  current_user.friends - @notecollection.users

     if @user.empty?
        respond_to do |format|
        format.html { redirect_to @notecollection, notice: 'The note has already been shared with all of   your friends' }
        end
    end
   end

     def createsharing
     @notecollection.user_ids = params["users"]["user_ids"] + (@notecollection.users).map{|u| u.id}
     redirect_to @notecollection
     end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notecollection
      @notecollection = Notecollection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notecollection_params
      params.require(:notecollection).permit(:name, :comment, :note_ids =>[], :user_ids =>[])
    end

     
end

app/helpers/notecollections_helper.rb
module NotecollectionsHelper
end

app/views/notecollections/_form.html.erb
<style>
.container{
    display: flex;
    justify-content: center;
    align-items: center;
}
</style>

<%= form_with(model: notecollection, local: true) do |form| %>
  <% if notecollection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(notecollection.errors.count, "error") %> prohibited this notecollection from being saved:</h2>

      <ul>
      <% notecollection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :name %>
    <%= form.text_field :name, id: :notecollection_name, :class => "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :comment %>
    <%= form.text_area :comment, id: :notecollection_comment , :class => "form-control"%>
  </div>

  <div class="form-group row">
  <%= collection_check_boxes(:notecollection, :note_ids, @note, :id, :text, :class => "form-control") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notecollections/edit.html.erb
<h1>Editing Notecollection</h1>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
<%= render 'form', notecollection: @notecollection %>
<div class="btn-group btn-group-toggle">
<%= link_to 'Show', @notecollection %> |
<%= link_to 'Back', notecollections_path %>
</div>
</div>
</div>

app/views/notecollections/index.html.erb
<!-- Portfolio Grid -->
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Note collections</h2>
        <h3 class="section-subheading text-muted">List of your note collections(created and shared with you).</h3>
        <%if !current_user.admin?%>
        <%= link_to 'New Note collections', new_notecollection_path , :class => "btn" %>
        <% end %>
      </div>
    </div>
    <div class="row">
    <% @notecollections.each do |notecollection| %>


      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#notecollection<%= notecollection.id %>">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <%= image_tag("folder.jpg", :alt => "",  size: "210") %>
        </a>
        <div class="portfolio-caption">
          <h4><%= notecollection.name %></h4>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<% @notecollections.each do |notecollection| %>
<div class="portfolio-modal modal fade" id="notecollection<%= notecollection.id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl"></div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
              <!-- Project Details Go Here -->

              <p class="item-intro text-muted"><h3>Note collection</h3></p>
                  <img class="img-fluid" src="app/assets/images/folder.jpg" alt="">
              <ul class="list-inline">
                <li><%= link_to 'Show', notecollection %></li>
                <li><%= link_to 'Edit', edit_notecollection_path(notecollection) %></li>
                <%if !current_user.admin?%>
                <li><%= link_to 'Share', new_sharing_notecollection_path(notecollection)  %></li>
                <% end %>
                <li><%= link_to 'Destroy', notecollection, method: :delete, data: { confirm: 'Are you sure?' } %></li>
              </ul>
              <button class="btn btn-primary" data-dismiss="modal" type="button">
                <i class="fa fa-times"></i>
                Close note collection</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/notecollections/new.html.erb
<h1>New Notecollection</h1>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
<%= render 'form', notecollection: @notecollection %>
<div class="btn-group btn-group-toggle">
<%= link_to 'Back', notecollections_path %>
</div>
</div>
</div>

app/views/notecollections/newsharing.html.erb
<h1>Sharing note collection</h1>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
<%= form_with url: create_sharing_notecollection_path do |form| %>

<div class="form-group row">
<%= collection_check_boxes(:users, :user_ids, @user, :id, :email,  :class => "form-control") %>
</div>

<div class="actions">
    <%= form.submit %>
</div>
<% end %>
</div>
</div>

app/views/notecollections/show.html.erb
<style>
.container{
    display: flex;
    justify-content: center;
    align-items: center;
}
</style>
<p id="notice"><%= notice %></p>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
  <div class="media-body">
    <h5 class="mt-0"><p>
  <strong> Name: </strong>
<h3>  <%= @notecollection.name %></h3>
</p>

<p>
  <strong>Comment:</strong>
  <%= @notecollection.comment %>
</p>

<table class="table table-striped ">
    <thead>
      <tr>
        <th scope="col">Image</th>
        <th scope="col">text</th>
      </tr>
    </thead>
    <tbody>
      <tr class="table-active">
      <% @notecollection.notes.each do |note| %>
      <td><%= image_tag note.image.url(:medium) %></td>
      <td><%= note.text %></td>
            </tr>
                  <%end%>
          </tbody>
        </table>
  <div class="btn-group btn-group-toggle">
  <% if !current_user.admin? %>
<%= link_to 'Edit', edit_notecollection_path(@notecollection) ,:class => "btn" %>
  <% end %>
<%= link_to 'Back', notecollections_path,:class => "btn" %>
<%= link_to 'Share', new_sharing_notecollection_path(@notecollection),:class => "btn"  %>
  </div>
</div>
</div>
</div>