config/routes.rb
Rails.application.routes.draw do
    get 'notes/:id/users', to: 'notes#newsharing' ,as: 'new_sharing_note'
  post 'notes/:id/users', to: 'notes#createsharing' ,as: 'create_sharing_note'
  get 'notecollections/:id/users', to: 'notecollections#newsharing' ,as: 'new_sharing_notecollection'
  post 'notecollections/:id/users', to: 'notecollections#createsharing' ,as: 'create_sharing_notecollection'
  resources :notecollections
  resources :notes
  root to: "notes#index"
  devise_for :users
    as :user do
        get '/users', to: 'users/sessions#index'
        #post '/users', to: 'users/registrations#create'
        #get '/users/new', to: 'users/registrations#new' , as: "new_user"
        get '/users/:id', to: 'users/sessions#show' , as: "user"
        get '/users/:id/edit', to: 'users/sessions#edit' , as: "edit_user"
        patch '/users/:id', to: 'users/sessions#update'
        post '/users/:id/acc', to: 'users/sessions#acceptfriend' ,as: 'acc_friend'
        post '/users/:id/add', to: 'users/sessions#addfriend' ,as: 'add_friend'
        post '/users/:id/rev', to: 'users/sessions#revokefriend' ,as: 'rev_friend'
        delete '/users/:id', to: 'users/sessions#destroy'
end

    get '/friendships', to: 'friendships#index'
    delete 'friendships/:id/destroy_friendship', to: 'friendships#destroy', as: 'destroy_friendship'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/
  has_and_belongs_to_many :notecollections
  has_and_belongs_to_many :users
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy,:newsharing,:createsharing]
  before_action :authenticate_user!
  # GET /notes
  # GET /notes.json
  def index
    if current_user.admin?
         @notes = Note.all
   else
    @notes = current_user.notes
  end
 end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)
    @note.users << current_user
    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully createdviao.' }
        format.json { render :show, status: :created, location: @note }
      else
        format.html { render :new }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { render :show, status: :ok, location: @note }
      else
        format.html { render :edit }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url, notice: 'Note was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

   def newsharing
     @user = current_user.friends - @note.users

     if @user.empty?
        respond_to do |format|
        format.html { redirect_to @note, notice: 'The note has already been shared with all of   your friends' }
        end
    end
   end

     def createsharing
     @note.user_ids = params["users"]["user_ids"] + (@note.users).map{|u| u.id}
     redirect_to @note
     end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:text,:image)
    end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<style>
.container{
    display: flex;
    justify-content: center;
    align-items: center;
}
</style>


<%= form_with(model: note, local: true, html: { multipart: true })   do |form| %>
  <% if note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% note.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <%= form.label :text %>
    <%= form.text_area :text, id: :note_text , :class => "form-control" %>
  </div>

  <div class="form-group row">
    <%= form.label :image %>
    <%= form.file_field :image , :class => "form-control-file"%>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing Note</h1>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
<%= render 'form', note: @note %>
<div class="btn-group btn-group-toggle">
<%= link_to 'Show', @note ,:class => "btn"%>
<%= link_to 'Back', notes_path, :class => "btn" %>
</div>
</div>
</div>

app/views/notes/index.html.erb
<!-- Portfolio Grid -->
<section class="bg-light" id="portfolio">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 text-center">
        <h2 class="section-heading text-uppercase">Notes</h2>
        <h3 class="section-subheading text-muted">List of your notes(created and shared with you).</h3>
        <%if !current_user.admin?%>
        <%= link_to 'New Note', new_note_path , :class => "btn" %>
        <% end %>
      </div>
    </div>
    <div class="row">
    <% @notes.each do |note| %>


      <div class="col-md-4 col-sm-6 portfolio-item">
        <a class="portfolio-link" data-toggle="modal" href="#note<%= note.id %>">
          <div class="portfolio-hover">
            <div class="portfolio-hover-content">
              <i class="fa fa-plus fa-3x"></i>
            </div>
          </div>
          <%= image_tag note.image.url(:medium) %>
        </a>
        <div class="portfolio-caption">
        <h4><%= note.text[0..20] %>...</h4>
        </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<% @notes.each do |note| %>
<div class="portfolio-modal modal fade" id="note<%= note.id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl"></div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
              <!-- Project Details Go Here -->

              <p class="item-intro text-muted"><h3>Note</h3></p>
                <%= image_tag note.image.url(:medium) %>
              <ul class="list-inline">
                <li><%= link_to 'Show', note ,  :class => "btn"%></li>
                <li><%= link_to 'Edit', edit_note_path(note),  :class => "btn" %></li>
                <%if !current_user.admin?%>
                <li><%= link_to 'Share', new_sharing_note_path(note) ,  :class => "btn" %></li>
                <% end %>
                <li><%= link_to 'Destroy', note, method: :delete, data: { confirm: 'Are you sure?' },  :class => "btn" %></li>
              </ul>
              <button class="btn btn-primary" data-dismiss="modal" type="button">
                <i class="fa fa-times"></i>
                Close note</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/notes/new.html.erb
<h1>New Note</h1>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
<%= render 'form', note: @note %>
<div class="btn-group btn-group-toggle">
<%= link_to 'Back', notes_path, :class => "btn" %>
</div>
</div>
</div>

app/views/notes/newsharing.html.erb
<h1>Sharing note</h1>
<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
<%= form_with url: create_sharing_note_path do |form| %>

<div class="form-group row">
<%= collection_check_boxes(:users, :user_ids, @user, :id, :email , :class => "form-control") %>
</div>

<div class="actions">
    <%= form.submit  %>
</div>
<% end %>
</div>
</div>

app/views/notes/show.html.erb
<style>
.container{
    display: flex;
    justify-content: center;
    align-items: center;
}
</style>
<p id="notice"><%= notice %></p>


<div class="container border border-dark shadow-lg p-4 mb-4 bg-white">
<div class="well well-lg">
  <%= image_tag @note.image.url(:medium), class: "align-self-start mr-3" %>

  <div class="media-body">
    <h5 class="mt-0"><p>
      <strong>Text:</strong>
      <%= @note.text %>
    </p></h5>
    <p>
    	<strong>Note shared with:</strong>
    	<%= @note.users.map {|u| u.name}.join(', ') %>
    </p>
    <div class="btn-group btn-group-toggle">
      <%= link_to 'Edit', edit_note_path(@note), :class => "btn" %>
      <% if !current_user.admin? %>
      <%= link_to 'Share', new_sharing_note_path(@note), :class => "btn" %>
      <% end %>
      <%= link_to 'Back', notes_path, :class => "btn" %>

    </div>
  </div>
</div>
</div>