config/routes.rb
Rails.application.routes.draw do
    get 'notes/:id/users', to: 'notes#newsharing' ,as: 'new_sharing_note'
  post 'notes/:id/users', to: 'notes#createsharing' ,as: 'create_sharing_note'
  get 'notecollections/:id/users', to: 'notecollections#newsharing' ,as: 'new_sharing_notecollection'
  post 'notecollections/:id/users', to: 'notecollections#createsharing' ,as: 'create_sharing_notecollection'
  resources :notecollections
  resources :notes
  root to: "notes#index"
  devise_for :users
    as :user do
        get '/users', to: 'users/sessions#index'
        #post '/users', to: 'users/registrations#create'
        #get '/users/new', to: 'users/registrations#new' , as: "new_user"
        get '/users/:id', to: 'users/sessions#show' , as: "user"
        get '/users/:id/edit', to: 'users/sessions#edit' , as: "edit_user"
        patch '/users/:id', to: 'users/sessions#update'
        post '/users/:id/acc', to: 'users/sessions#acceptfriend' ,as: 'acc_friend'
        post '/users/:id/add', to: 'users/sessions#addfriend' ,as: 'add_friend'
        post '/users/:id/rev', to: 'users/sessions#revokefriend' ,as: 'rev_friend'
        delete '/users/:id', to: 'users/sessions#destroy'
end

    get '/friendships', to: 'friendships#index'
    delete 'friendships/:id/destroy_friendship', to: 'friendships#destroy', as: 'destroy_friendship'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <p><strong>This form contains <%= pluralize(object.errors.count, 'error') %>.</strong></p>
      <ul>
        <% object.errors.full_messages.each do |msg| %>
          <li><%=  "-".html_safe+" "+msg %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SocialNote</title>
    <%= csrf_meta_tags %>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" type="image/png" href="<%= image_path('icons/favicon.svg')%>"/>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
<% if user_signed_in? %>
  <nav class="navbar navbar-dark bg-dark">
      <%= link_to 'Profile', user_path(current_user), class: "nav-item nav-link" %>
  <%= link_to 'Note', notes_path, class: "nav-item nav-link" %>
  <%= link_to 'Note collections', notecollections_path, class: "nav-item nav-link" %>

 <%= link_to 'Users', users_path, class: "nav-item nav-link" %>
  <%if current_user.admin?%>
     <%= link_to 'Friendships', friendships_path, class: "nav-item nav-link" %>
  <%end %>

 <%= link_to 'Logout', destroy_user_session_path, method: :delete , class: "nav-item nav-link"%>
</nav>
<% end %>
    <%= yield %>
  </body>
</html>